# Generated by Django 5.2.7 on 2025-12-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
