# Generated by Django 5.2.7 on 2025-12-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0002_level_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
