# Generated by Django 5.2.7 on 2025-12-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0003_alter_level_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
