# Generated by Django 5.2.7 on 2025-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0004_level_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order_txt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
