# Generated by Django 5.2.7 on 2025-12-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0006_remove_topic_order_txt_topic_order_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='order_num',
        ),
        migrations.AddField(
            model_name='topic',
            name='order_txt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
