# Generated by Django 5.2.7 on 2025-12-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0007_remove_topic_order_num_topic_order_txt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrase',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
