# Generated by Django 5.2.7 on 2025-12-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0008_alter_phrase_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='trainer/course_icons/'),
        ),
    ]
