# Generated by Django 5.2.7 on 2025-12-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0010_phrasefavorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phrase',
            old_name='mp3',
            new_name='sound',
        ),
    ]
