# Generated by Django 5.2.7 on 2025-12-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0011_rename_mp3_phrase_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phrasefavorite',
            name='phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer_phrase_favorites', to='train.phrase'),
        ),
    ]
