# Generated by Django 5.2.7 on 2026-01-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0012_alter_phrasefavorite_phrase'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='trainer/mp3'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='trainer/phrase'),
        ),
    ]
