# Generated by Django 5.2.7 on 2026-01-13 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0013_audiofile_file_phrase_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Обобщающий'),
        ),
    ]
