# Generated by Django 5.2.7 on 2026-01-13 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0014_topic_is_common'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order_txt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
