# Generated by Django 5.2.7 on 2026-01-13 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0015_alter_audiofile_order_alter_topic_order_txt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='order',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='order_txt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
