# Generated by Django 5.2.7 on 2026-01-16 14:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0017_alter_audiofile_order_alter_audiofile_slug_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='audiofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trainer_audio_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phrase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_ru'], name='trainer_phrase_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phrase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_en'], name='trainer_phrase_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='trainer_topic_name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
