# Generated by Django 5.2.7 on 2026-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0018_audiofile_trainer_audio_name_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Номер ПП'),
        ),
    ]
