# Generated by Django 5.2.7 on 2026-01-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0019_level_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['-order_num']},
        ),
    ]
