# Generated by Django 5.2.7 on 2026-01-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('train', '0020_alter_level_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order_num']},
        ),
    ]
