# Generated by Django 5.2.7 on 2025-12-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug курса')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название группы')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название урока')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug урока')),
                ('url', models.URLField(max_length=500, verbose_name='URL урока')),
                ('mp3', models.URLField(blank=True, null=True, verbose_name='Аудио MP3 урока')),
            ],
        ),
        migrations.CreateModel(
            name='DictionaryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст на русском')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст на английском')),
                ('sound', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудио')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lesson.dictionarygroup', verbose_name='Группа слов')),
            ],
        ),
        migrations.AddField(
            model_name='dictionarygroup',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dictionary_groups', to='lesson.lesson', verbose_name='Урок'),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название уровня')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug уровня')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание уровня')),
                ('url', models.URLField(max_length=500, verbose_name='URL уровня')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='lesson.course', verbose_name='Курс')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='lesson.level', verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название модуля')),
                ('index', models.CharField(blank=True, max_length=20, null=True, verbose_name='Индекс модуля')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='URL модуля')),
                ('sorting', models.IntegerField(blank=True, null=True, verbose_name='Порядок отображения модуля')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='lesson.lesson', verbose_name='Урок')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sorting', models.IntegerField(blank=True, null=True, verbose_name='Сортировка блока')),
                ('caption', models.TextField(blank=True, null=True, verbose_name='Текст/описание блока')),
                ('type3_content', models.JSONField(blank=True, default=list, verbose_name='HTML контент блока (type3)')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='lesson.module', verbose_name='Модуль')),
            ],
        ),
        migrations.CreateModel(
            name='LessonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст на русском')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст на английском')),
                ('sound', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудио')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lesson.moduleblock', verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_src', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='lesson.moduleblock', verbose_name='Блок')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время начала')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время конца')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Текст на английском')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Текст на русском')),
                ('sound', models.URLField(blank=True, null=True, verbose_name='Ссылка на аудио')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='lesson.video', verbose_name='Видео')),
            ],
        ),
    ]
