# Generated by Django 5.2.7 on 2025-12-22 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание урока'),
        ),
    ]
