# Generated by Django 5.2.7 on 2025-12-22 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0002_lesson_short_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['sorting']},
        ),
        migrations.AddField(
            model_name='module',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('da2c4c9e-53b8-468e-92a6-c068aa947b11'), editable=False),
        ),
    ]
