# Generated by Django 5.2.7 on 2025-12-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0003_alter_module_options_module_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='uuid',
        ),
    ]
