# Generated by Django 5.2.7 on 2025-12-23 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0005_alter_moduleblock_options_moduleblockdone_moduledone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleblockdone',
            old_name='module',
            new_name='module_block',
        ),
    ]
