# Generated by Django 5.2.7 on 2025-12-23 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0006_rename_module_moduleblockdone_module_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ModuleDone',
            new_name='LessonDone',
        ),
        migrations.RemoveField(
            model_name='lessondone',
            name='module',
        ),
        migrations.AddField(
            model_name='lessondone',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lesson'),
        ),
    ]
