# Generated by Django 5.2.7 on 2025-12-23 13:13

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0007_rename_moduledone_lessondone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionarygroup',
            name='module_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_block_dictionary_groups', to='lesson.moduleblock', verbose_name='Блок модуля'),
        ),
        migrations.AlterField(
            model_name='moduleblock',
            name='type3_content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='HTML контент блока (type3)'),
        ),
    ]
