# Generated by Django 5.2.7 on 2025-12-23 13:14

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0008_dictionarygroup_module_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleblock',
            name='caption',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст/описание блока'),
        ),
    ]
