# Generated by Django 5.2.7 on 2025-12-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0009_alter_moduleblock_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryitem',
            name='sound',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на аудио'),
        ),
    ]
