# Generated by Django 5.2.7 on 2025-12-23 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0010_alter_dictionaryitem_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionarygroup',
            name='module_block',
        ),
        migrations.AddField(
            model_name='dictionarygroup',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='module_dictionary_groups', to='lesson.module', verbose_name='Блок модуля'),
        ),
    ]
