# Generated by Django 5.2.7 on 2025-12-25 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0013_phrasefavoriteitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhraseFavoriteItem',
            new_name='LessonItemFavoriteItem',
        ),
        migrations.RemoveField(
            model_name='lessonitemfavoriteitem',
            name='phrase',
        ),
        migrations.AddField(
            model_name='lessonitemfavoriteitem',
            name='lesson_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.lessonitem'),
        ),
    ]
