# Generated by Django 5.2.7 on 2025-12-29 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0014_rename_phrasefavoriteitem_lessonitemfavoriteitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='lessons/course_covers/'),
        ),
        migrations.AddField(
            model_name='level',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='lessons/level_icons/'),
        ),
        migrations.AlterField(
            model_name='lessonitemfavoriteitem',
            name='lesson_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_item_favorites', to='lesson.lessonitem'),
        ),
    ]
