# Generated by Django 5.2.7 on 2025-12-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0015_course_cover_level_icon_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionarygroup',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='dictionarygroup',
            name='order',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
