# Generated by Django 5.2.7 on 2025-12-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0016_alter_dictionarygroup_options_dictionarygroup_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dictionarygroup',
            options={'ordering': ['-order', 'id']},
        ),
        migrations.AddField(
            model_name='moduleblock',
            name='cab_be_done',
            field=models.BooleanField(default=True, verbose_name='Выполняемыей'),
        ),
    ]
