# Generated by Django 5.2.7 on 2025-12-30 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0017_alter_dictionarygroup_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moduleblock',
            old_name='cab_be_done',
            new_name='can_be_done',
        ),
    ]
