# Generated by Django 5.2.7 on 2026-01-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0018_rename_cab_be_done_moduleblock_can_be_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/dictionary/mp3'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/mp3/'),
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/module/mp3/'),
        ),
        migrations.AddField(
            model_name='phrase',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/module/video/phrase'),
        ),
        migrations.AddField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/module/video/'),
        ),
    ]
