# Generated by Django 5.2.7 on 2026-01-16 14:50

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0020_orthographyitem_orthographyitemdone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dictionaryitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_ru'], name='dict_text_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='dictionaryitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_en'], name='dict_text_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='lesson_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lessonitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_ru'], name='lessonitem_text_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='lessonitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_en'], name='lessonitem_text_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='module',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title'], name='module_title_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='orthographyitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['ru_text'], name='ortho_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='orthographyitem',
            index=django.contrib.postgres.indexes.GinIndex(fields=['en_text'], name='ortho_en_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phrase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_ru'], name='lesson_phrase_text_ru_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='phrase',
            index=django.contrib.postgres.indexes.GinIndex(fields=['text_en'], name='lesson_phrase_text_en_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
