# Generated by Django 5.2.7 on 2026-01-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0021_dictionaryitem_dict_text_ru_trgm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
