# Generated by Django 5.2.7 on 2026-01-18 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0022_video_video_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='table',
            field=models.TextField(blank=True, null=True),
        ),
    ]
