# Generated by Django 5.2.7 on 2026-01-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0023_lesson_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='orthography_description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание блока орфографии'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='table_file',
            field=models.ImageField(blank=True, null=True, upload_to='lesson/table'),
        ),
    ]
