# Generated by Django 5.2.7 on 2026-01-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0024_lesson_orthography_description_lesson_table_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL урока'),
        ),
        migrations.AlterField(
            model_name='level',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL уровня'),
        ),
    ]
