# Generated by Django 5.2.7 on 2026-01-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0025_alter_lesson_url_alter_level_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
