# Generated by Django 5.2.7 on 2026-01-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0026_course_bg_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['order_num']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Номер ПП'),
        ),
        migrations.AddField(
            model_name='level',
            name='order_num',
            field=models.IntegerField(default=0, verbose_name='Номер ПП'),
        ),
    ]
