# Generated by Django 5.2.7 on 2026-01-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0027_alter_lesson_options_alter_level_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-order_num']},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['-order_num']},
        ),
    ]
