# Generated by Django 5.2.7 on 2026-01-26 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0029_alter_lesson_options_alter_level_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_common',
            field=models.BooleanField(default=False, verbose_name='Обобщающий'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Бесплатный'),
        ),
    ]
