# Generated by Django 5.2.7 on 2026-01-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0030_lesson_is_common_lesson_is_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='mp3',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Аудио MP3 урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, editable=False, max_length=500, null=True, verbose_name='URL урока'),
        ),
        migrations.AlterField(
            model_name='phrase',
            name='sound',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Ссылка на аудио'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_src',
            field=models.URLField(blank=True, editable=False, null=True, verbose_name='Ссылка на видео'),
        ),
    ]
