# Generated by Django 5.2.7 on 2026-02-05 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0031_alter_lesson_mp3_alter_lesson_url_alter_phrase_sound_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, null=True)),
                ('is_for_school', models.BooleanField(default=False)),
                ('is_decorated', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, max_length=30, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('price_text', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TariffItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lesson.tariff')),
            ],
        ),
    ]
