# Generated by Django 5.2.7 on 2026-02-05 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0032_tariff_tariffitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariffitem',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_items', to='lesson.tariff'),
        ),
    ]
