# Generated by Django 6.0.2 on 2026-02-27 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0033_alter_tariffitem_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время начала')),
                ('end_time', models.CharField(blank=True, max_length=20, null=True, verbose_name='Время конца')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст ')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watermarks', to='lesson.video', verbose_name='Видео')),
            ],
        ),
    ]
