# Generated by Django 6.0.2 on 2026-03-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0034_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='progress_bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='progress_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
