# Generated by Django 6.0.2 on 2026-03-06 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0035_course_progress_bg_color_course_progress_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessonitem',
            options={'ordering': ['order_num']},
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='order_num',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
