# Generated by Django 6.0.2 on 2026-03-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0036_alter_lessonitem_options_lessonitem_order_num'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phrase',
            options={'ordering': ['id']},
        ),
    ]
