# Generated by Django 6.0.2 on 2026-03-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0037_alter_phrase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleblock',
            name='can_be_done',
            field=models.BooleanField(default=True, verbose_name='Выполняемый'),
        ),
    ]
