# Generated by Django 5.2.7 on 2025-12-22 12:32

import django.db.models.deletion
import django.utils.timezone
import user.models.user
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_school', models.BooleanField(default=False, verbose_name='Это школа')),
                ('uuid', models.UUIDField(default=uuid.UUID('e2d472e3-17cc-419d-b368-c51ec50f1727'), editable=False)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars')),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Почта')),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Логин')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Коментарий')),
                ('subscription_expire', models.DateField(blank=True, null=True, verbose_name='Подписка до')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': '1. Пользователи',
            },
            managers=[
                ('objects', user.models.user.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('453325e2-9a87-4e62-93ef-e27399545170'), editable=False)),
                ('name', models.CharField(max_length=100)),
                ('pupils', models.ManyToManyField(blank=True, related_name='pupils', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.school'),
        ),
    ]
