# Generated by Django 5.2.7 on 2025-12-22 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ca58bc11-1536-4b7e-8044-fdd1e3bf0650'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9767964d-2b95-44fe-b8b0-30b938b7c005'), editable=False),
        ),
    ]
