# Generated by Django 5.2.7 on 2025-12-22 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9397604d-bbe0-42f6-bda3-be486f716629'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('35a74fb6-ebab-45b9-bf7b-4130ca2c1509'), editable=False),
        ),
    ]
