# Generated by Django 5.2.7 on 2025-12-22 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8e7aca78-f0f5-469b-b2e2-2d03ba196f75'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('abb42ea9-27d6-435f-aaaa-5fc4f84d8b27'), editable=False),
        ),
    ]
