# Generated by Django 5.2.7 on 2025-12-23 08:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c8eda925-ba10-4f5f-af51-880d20be5a63'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('aaead046-ca24-452a-b64a-dd125d8046c6'), editable=False),
        ),
    ]
