# Generated by Django 5.2.7 on 2025-12-23 08:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6bb6e2ae-b051-469d-bf63-e6baaa7314d2'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f5a46811-a576-431a-9a23-f574e6133b3a'), editable=False),
        ),
    ]
