# Generated by Django 5.2.7 on 2025-12-23 12:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c37c6ed-79f4-44c0-84b2-bf53eac0803f'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0e06b7e4-941a-489b-b7e1-19a53f6b1073'), editable=False),
        ),
    ]
