# Generated by Django 5.2.7 on 2025-12-23 13:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f716e19b-e666-45f9-b6a1-c8a3f070ed76'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6cc5a557-5122-4495-a4eb-d817843bbf74'), editable=False),
        ),
    ]
