# Generated by Django 5.2.7 on 2025-12-23 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9322ac41-ddf8-474f-8c8b-7b50392102c2'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3ff4b852-034a-4ad1-9802-134eda9d1db8'), editable=False),
        ),
    ]
