# Generated by Django 5.2.7 on 2025-12-23 13:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('035d3031-0926-4246-8152-0aa2f335c946'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9b6c45cd-1450-466e-81a4-a446a8b474ca'), editable=False),
        ),
    ]
