# Generated by Django 5.2.7 on 2025-12-23 13:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('32fe32cd-87fc-4864-b8c6-18be8679d46c'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('411348ab-4bac-48ae-a01a-8cd92cdcc4c3'), editable=False),
        ),
    ]
