# Generated by Django 5.2.7 on 2025-12-24 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_lesson_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3935e29c-964e-49d0-877e-c1ae57b655ae'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('99b6e77e-e603-45eb-a8b2-a384b702cf93'), editable=False),
        ),
    ]
