# Generated by Django 5.2.7 on 2025-12-24 08:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_last_lesson_url_alter_school_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('7581573f-4405-45e4-bc54-c1460d278b99'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('430203f2-f5fc-460d-8b05-f16ecbc8cea1'), editable=False),
        ),
    ]
