# Generated by Django 5.2.7 on 2025-12-24 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d97f622c-1e71-4bd6-85d8-074728194147'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9a76d10e-fd37-4564-9ed8-1487295f820c'), editable=False),
        ),
    ]
