# Generated by Django 5.2.7 on 2025-12-24 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c60d07d5-ad96-4317-bd5d-66dcfffe7596'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4f0bcf7e-d4f0-40ce-b9a9-2f27018f0aa0'), editable=False),
        ),
    ]
