# Generated by Django 5.2.7 on 2025-12-24 16:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4091e717-7954-4a1f-9598-2a7dd27e4e5f'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c0df248a-da4a-471b-a740-97878de95ebe'), editable=False),
        ),
    ]
