# Generated by Django 5.2.7 on 2025-12-24 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d4b076e5-ec46-42c9-9c31-aa2527e3ef93'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dcab50ef-8967-4c0c-b3ac-108dd4fa2e4a'), editable=False),
        ),
    ]
