# Generated by Django 5.2.7 on 2025-12-24 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('71c5deb6-27b8-42ab-8538-671daefbbd57'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('59ce89b0-da30-40b6-b351-65662c8e4731'), editable=False),
        ),
    ]
