# Generated by Django 5.2.7 on 2025-12-24 17:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c99b4065-99c0-4b69-b5c9-1eef7372d00a'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('73435dd6-2ed9-4107-b121-528a3c0782a3'), editable=False),
        ),
    ]
