# Generated by Django 5.2.7 on 2025-12-24 17:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dd671949-b145-4f1d-b239-13b861523553'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('906cd9d7-5d4b-46e6-bf24-182d6db01790'), editable=False),
        ),
    ]
