# Generated by Django 5.2.7 on 2025-12-24 17:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('37d1a7bc-7a4f-4ad3-be79-66c3dfba09e7'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('435bd659-1901-4839-8e85-fe6bc5322b5b'), editable=False),
        ),
    ]
