# Generated by Django 5.2.7 on 2025-12-24 17:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ed8eac09-6906-4ce3-a150-8c9b8956a5d6'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('dff97da3-d9dc-442c-8c11-485b96df2076'), editable=False),
        ),
    ]
