# Generated by Django 5.2.7 on 2025-12-25 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6c30f05d-69e4-4d42-9e48-7b5dec4668d3'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e43a6977-db78-4040-88da-db9efcb98399'), editable=False),
        ),
    ]
