# Generated by Django 5.2.7 on 2025-12-25 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1c8c034f-5aa8-4bf9-889a-91edd743129d'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4748f80b-708e-4342-8dee-54ecebc9d3d8'), editable=False),
        ),
    ]
