# Generated by Django 5.2.7 on 2025-12-25 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d93db6be-3eed-4078-8d5c-c0c196536c1a'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('bc947685-39cf-4c37-8c4f-67291c6b58f5'), editable=False),
        ),
    ]
