# Generated by Django 5.2.7 on 2025-12-25 15:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('4132f2cd-2523-4d53-b1d6-8810286c3330'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3b4920dd-f82b-4211-88fa-09fe49e5b98c'), editable=False),
        ),
    ]
