# Generated by Django 5.2.7 on 2025-12-25 15:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fd1e5f9a-9b66-4752-b86e-63e119a72137'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d8753f65-735d-4d5e-80a7-74ed56b2a8df'), editable=False),
        ),
    ]
