# Generated by Django 5.2.7 on 2025-12-29 12:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('9376a71e-fec6-400d-8f10-0d923e6f94f7'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c71e8357-709b-4ad0-8a28-2748bb55caca'), editable=False),
        ),
    ]
