# Generated by Django 5.2.7 on 2025-12-29 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2262abf9-8290-47a8-9398-eb5cdfd468a7'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('8a64161f-2021-4ab9-8d51-cdcdacc31b2e'), editable=False),
        ),
    ]
