# Generated by Django 5.2.7 on 2025-12-30 07:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3673a4e0-9b5c-49f5-bf62-6f2d313608fc'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('5c737ee6-dc03-4d54-8720-005a39c272bb'), editable=False),
        ),
    ]
