# Generated by Django 5.2.7 on 2025-12-30 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('54c68bf5-bf94-4ffe-ba49-634b6d587009'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('05c5058a-ef5a-427b-861e-6da9bbc3a127'), editable=False),
        ),
    ]
