# Generated by Django 5.2.7 on 2026-01-06 07:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('fc366542-c26e-4fc2-9694-924a9bc2304d'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6da7b23b-36d9-4e25-9822-4c7127ab8092'), editable=False),
        ),
    ]
