# Generated by Django 5.2.7 on 2026-01-12 10:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0032_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('987f062a-6257-4d39-9659-5162fe549681'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1e840b82-2a03-49ae-b031-b8ddd7b71849'), editable=False),
        ),
    ]
