# Generated by Django 5.2.7 on 2026-01-13 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_school_uuid_alter_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c5880892-2b23-4c08-9bbf-5c54ac0cb397'), editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('d071a814-8851-44e8-9bef-1a52e93430f8'), editable=False),
        ),
    ]
