# Generated by Django 5.2.7 on 2026-01-16 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_usertoken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertoken',
            options={'verbose_name': 'Токен авторизации', 'verbose_name_plural': 'Токены авторизации'},
        ),
        migrations.AddField(
            model_name='school',
            name='admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
