# Generated by Django 5.2.7 on 2026-01-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_alter_usertoken_options_school_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='max_logins',
            field=models.IntegerField(default=5, null=True, verbose_name='Одновременное кол-во подключений'),
        ),
    ]
