# Generated by Django 6.0.2 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_user_max_logins'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='school/images'),
        ),
        migrations.AddField(
            model_name='school',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug урока'),
        ),
    ]
